"""cria contas recorrentes

Revision ID: 0e754ffa042d
Revises: 78164d6a7d96
Create Date: 2026-05-26 11:26:00.860314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e754ffa042d'
down_revision = '78164d6a7d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas_equipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas_equipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('responsavel', sa.VARCHAR(length=100), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('dia_semana', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
