"""create radar financeiro manual

Revision ID: 78164d6a7d96
Revises: 9296f1434b2b
Create Date: 2026-05-21 11:11:10.281796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78164d6a7d96'
down_revision = '9296f1434b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_radar_financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=150), nullable=True),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('gerado_por_transporte', sa.Boolean(), nullable=True),
    sa.Column('conta_origem_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_origem_id'], ['contas_radar_financeiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas_radar_financeiro')
    # ### end Alembic commands ###
