"""add conciliacao importacoes financeiras

Revision ID: 9296f1434b2b
Revises: d29f8aa39a8f
Create Date: 2026-05-21 10:01:54.627778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9296f1434b2b'
down_revision = 'd29f8aa39a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_pagar_importadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_conciliacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('origem_importacao', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_contas_pagar_importadas_chave_conciliacao'), ['chave_conciliacao'], unique=False)

    with op.batch_alter_table('contas_receber_importadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_conciliacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('origem_importacao', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_contas_receber_importadas_chave_conciliacao'), ['chave_conciliacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_receber_importadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_receber_importadas_chave_conciliacao'))
        batch_op.drop_column('origem_importacao')
        batch_op.drop_column('chave_conciliacao')

    with op.batch_alter_table('contas_pagar_importadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_pagar_importadas_chave_conciliacao'))
        batch_op.drop_column('origem_importacao')
        batch_op.drop_column('chave_conciliacao')

    # ### end Alembic commands ###
