"""adiciona imagens em manutencoes

Revision ID: 98fd57819edd
Revises: e6a24723f55f
Create Date: 2026-05-06 10:32:08.898720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fd57819edd'
down_revision = 'e6a24723f55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagens', sa.Text(), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagens')

    # ### end Alembic commands ###
