"""adiciona parcelas no radar financeiro

Revision ID: c3d1fcb84b60
Revises: 0e754ffa042d
Create Date: 2026-05-26 16:07:07.611433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d1fcb84b60'
down_revision = '0e754ffa042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_pagar_importadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_obrigacao', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('parcela_atual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_parcelas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grupo_parcelamento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dia_vencimento_parcela', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcela_origem_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contas_pagar_importadas_grupo_parcelamento'), ['grupo_parcelamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas_pagar_importadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_pagar_importadas_grupo_parcelamento'))
        batch_op.drop_column('parcela_origem_id')
        batch_op.drop_column('dia_vencimento_parcela')
        batch_op.drop_column('grupo_parcelamento')
        batch_op.drop_column('total_parcelas')
        batch_op.drop_column('parcela_atual')
        batch_op.drop_column('tipo_obrigacao')

    # ### end Alembic commands ###
