"""adiciona data_saida e causa em manutencoes

Revision ID: d16f3ba37998
Revises: f31df94a9278
Create Date: 2026-05-06 10:09:22.865701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16f3ba37998'
down_revision = 'f31df94a9278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_saida', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('causa', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.drop_column('causa')
        batch_op.drop_column('data_saida')

    # ### end Alembic commands ###
