"""add problema field

Revision ID: d29f8aa39a8f
Revises: 98fd57819edd
Create Date: 2026-05-13 08:49:40.693906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29f8aa39a8f'
down_revision = '98fd57819edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problema', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.drop_column('problema')

    # ### end Alembic commands ###
