"""adiciona imagem em manutencoes

Revision ID: e6a24723f55f
Revises: d16f3ba37998
Create Date: 2026-05-06 10:12:50.568819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a24723f55f'
down_revision = 'd16f3ba37998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
